blank_issues_enabled: false
contact_links:
  - name: Feature request
    url: https://github.com/getarcaneapp/arcane/discussions/new?category=feature-requests
    about: Suggest a new feature or enhancement for Arcane
  - name: Track the Most Upvoted Features
    url: https://github.com/getarcaneapp/arcane/discussions/categories/feature-requests
    about: Browse feature requests and upvote proposals in Discussions
  - name: 💬 Discord
    url: https://discord.gg/WyXYpdyV3Z
    about: For help and chatting with the community
